### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 48.00 GiB 

### ISSUE THREAD

**Issue by jiaxiangshang** [facebookresearch/pytorch3d#1193]
Originally, I am Pytorch 1.6 + cuda 10.1 + pytorch3d 0.3
Now I upgrade this to Pytorch 1.11 + cuda 11.3 + Pytorch3d 0.6

For the same python script, I got the out of memory error with allocating 48 GB, could you give some suggestions?

`RuntimeError: CUDA out of memory. Tried to allocate 48.00 GiB (GPU 0; 15.74 GiB total capacity; 667.01 MiB already allocated; 12.49 GiB free; 688.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

Best
Jiaxiang

**Comment by bottler** [comment]
Different versions of cuda/pytorch/pytorch3d use different amounts of memory so regressions can happen. But 48GB is much too much. What is trying to allocate that much?

**Comment by jiaxiangshang** [comment]
Hi bottler, thanks for your quick reply

I use the pytorch3d file from  https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py37_cu113_pyt1110/download.html
Which request pytorch 1,11 and cuda 11,3, that is why I upgrade these. I do not install pyt3d by conda, since I have alrealy have a stable conda env, I want to add pyt3d in it.

For 48GB, 
(1) I first tried pyt3d on a easy tiny optimization task, it works well
(2) I try to train an 3D face reconstruction network with Resnet 50, it output above error.
Do you have some suggestions to locate/print the allocate of GPU meomory, I do not find some good ways.

Best
Jiaxiang

**Comment by bottler** [comment]
When you get the error, do you also get a Traceback? Could you run the code in a debugger?

It might be a good idea to set the environment variable `CUDA_LAUNCH_BLOCKING`, as that can make CUDA errors easier to understand. But in this particular case I don't expect that to make a difference, because I think the allocation failure isn't coming from inside a cuda kernel.

I think the problem here is a single allocation of 48GB. That's much larger than any normal allocation. It's much larger than resnet-50. Something huge may be being moved to the GPU by mistake. Could a dataset be being moved to the GPU by mistake?

**Comment by jiaxiangshang** [comment]
I first try to put the Traceback here, and I print the shape of tensor in the line of break code
The line is `angle = F.relu(torch.sum(normals * direction, dim=-1))`
And the shape of normals and direction is `torch.Size([1, 256, 256, 1, 3]) torch.Size([65536, 1, 1, 1, 3])`

`Traceback (most recent call last):
  File "test_oneimage.py", line 172, in <module>
    _, inter_visual, inter_test = model(pyt_image, global_step)
  File "/home/jshang/anaconda3/envs/mdfsnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jshang/anaconda3/envs/mdfsnet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/jshang/anaconda3/envs/mdfsnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/is/cluster/jshang/workspace/recaugnet/net/6_resnet34_semi_seg_85_online.py", line 226, in forward
    flag_lighting=False)
  File "/is/cluster/jshang/workspace/a_baselib/pytorch/render/api_pyt3d_facescape.py", line 178, in render_mdfsnetDepth_trainPhase
    render, render_depth = h_render(mesh, znear=znear, zfar=zfar)
  File "/home/jshang/anaconda3/envs/mdfsnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/is/cluster/jshang/workspace/a_baselib/pytorch/render/pr_pyt3d/mesh/pyt3d_renderer.py", line 35, in forward
    images = self.shader(fragments, meshes_world, **kwargs)
  File "/home/jshang/anaconda3/envs/mdfsnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jshang/anaconda3/envs/mdfsnet/lib/python3.7/site-packages/pytorch3d/renderer/mesh/shader.py", line 131, in forward
    materials=materials,
  File "/home/jshang/anaconda3/envs/mdfsnet/lib/python3.7/site-packages/pytorch3d/renderer/mesh/shading.py", line 91, in phong_shading
    pixel_coords, pixel_normals, lights, cameras, materials
  File "/home/jshang/anaconda3/envs/mdfsnet/lib/python3.7/site-packages/pytorch3d/renderer/mesh/shading.py", line 32, in _apply_lighting
    light_diffuse = lights.diffuse(normals=normals, points=points)
  File "/home/jshang/anaconda3/envs/mdfsnet/lib/python3.7/site-packages/pytorch3d/renderer/lighting.py", line 276, in diffuse
    return diffuse(normals=normals, color=self.diffuse_color, direction=direction)
  File "/home/jshang/anaconda3/envs/mdfsnet/lib/python3.7/site-packages/pytorch3d/renderer/lighting.py", line 73, in diffuse
    angle = F.relu(torch.sum(normals * direction, dim=-1))
RuntimeError: CUDA out of memory. Tried to allocate 48.00 GiB (GPU 0; 15.74 GiB total capacity; 667.01 MiB already allocated; 12.50 GiB free; 688.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by jiaxiangshang** [comment]
The input is one image, so it can not be dataset problems

**Comment by bottler** [comment]
Something is wrong with the shape of some tensors here. I think you are trying to render one mesh into a 256*256 image. `direction` should have shape `[1, 256, 256, 1, 3]` not `[65536, 1, 1, 1, 3]` so that that multiplication output contains `3 * 256^2` elements not `3 * 256^4` elements. Can you work backwards (in a debugger or by adding print statements)?

The next step is probably looking at the shape of `normals` and trying to see why it is what it is.

Another approach would be to paste here the calls your code makes to the pytorch3d api: I.e. the calls you make to construct the renderer and the mesh and to call the renderer, and the shapes of all tensors involved in those calls. That might allow a simple reproduction of the problem.

It looks like you've renamed some of the files inside pytorch3d. Is that significant

**Comment by bottler** [comment]
Can you print the shapes of `normals` and `direction` at the beginning of the `diffuse` function?

**Comment by jiaxiangshang** [comment]
1. normal shape : torch.Size([1, 256, 256, 1, 3]) direction shape: torch.Size([1, 1, 256, 256, 1, 3])
2. The input is the mesh object of pyt3d, camera, the rasterizer and shader is all from pyt3d.
I renamed some files to add some api as output depth map, I put the code here
(1) build render
`
raster_settings, lights, blend_params = build_rendering_comnmon(image_size, device, flag_lighting, background_color=background_color)
    renderer = MeshRendererWithDepth(
        rasterizer=MeshRasterizer(
            cameras=cameras,
            raster_settings=raster_settings
        ),
        shader=SoftPhongShader(
            device=device,
            cameras=cameras,
            lights=lights,
            blend_params=blend_params
        )
    )
    return renderer
`
(2) build mesh and call renderer above
`
mesh = Meshes(verts=pred_mm_vertices[:, self.h_lrgp.h_curr.idx_subTopo.to(device)], faces=pyt_faceFore_tri,                      textures=tex)
render, render_depthmap = h_render(mesh, znear=znear, zfar=zfar)
`

If the normal is wrong, I guess it may because of the Mesh definition is changed during upgrade?

**Comment by jiaxiangshang** [comment]
vertex shape: torch.Size([1, 35157, 3])
tri shape: torch.Size([1, 53412, 3])
`tex = TexturesVertex(verts_features=FORE_color_light) `
FORE_color_light shape: torch.Size([1, 35157, 3])

**Comment by bottler** [comment]
direction shape should be torch.Size([1, 256, 256, 1, 3]). It has an extra 1. Maybe the light location was initialised wrong. Can you print the code that initialised the PointLights (and its tensor shapes)?

Maybe at the beginning of the diffuse function in PointLights, you could `print(normals.shape, points.shape, self.location.shape)`

**Comment by jiaxiangshang** [comment]
Because I use SH function, so I just open ambient light
`
        ambient_color = ((1.0, 1.0, 1.0),),
        diffuse_color = ((0.0, 0.0, 0.0),),
        specular_color = ((0.0, 0.0, 0.0),),
        location = ((0, 0, 5500),),
        lights = PointLights(device=device, ambient_color=ambient_color, diffuse_color=diffuse_color,
                             specular_color=specular_color, location=location)
`

print(normals.shape, points.shape, self.location.shape)
`
torch.Size([1, 256, 256, 1, 3]) torch.Size([1, 256, 256, 1, 3]) torch.Size([1, 1, 3])
`

**Comment by bottler** [comment]
Location should have size (1,3). I think you might an unwanted comma at the end of the definition of `location`. On its own line, you could write
```
location = ((0, 0, 5500),)
```

**Comment by jiaxiangshang** [comment]
It works now.

For the reason of my fault is:
I copy the default param below, but the comma's meaning is different.
`class PointLights(TensorProperties):
    def __init__(
        self,
        ambient_color=((0.5, 0.5, 0.5),),
        diffuse_color=((0.3, 0.3, 0.3),),
        specular_color=((0.2, 0.2, 0.2),),
        location=((0, 1, 0),),`

In the old version, it may pass, while the upgrade version of pytorch3d seems has a better formulation of lighting, that this problem appears.

Finally, bottler, super thanks for your kind help. It helps me a lot.

Best
Jiaxiang
