### ISSUE TITLE
CUDA error: operation not supported when calling ’cusparseCreate(handle)' on 4090 GPU

### ISSUE THREAD

**Issue by Vegetebird** [facebookresearch/pytorch3d#1399]
On my 4090 GPU, I got
```
File "/home/bird/anaconda3/envs/mmhuman3d_4090/lib/python3.9/site-packages/pytorch3d/renderer/mesh/rasterizer.py", line 227, in forward
    meshes_proj = self.transform(meshes_world, **kwargs)
  File "/home/bird/anaconda3/envs/mmhuman3d_4090/lib/python3.9/site-packages/pytorch3d/renderer/mesh/rasterizer.py", line 204, in transform
    to_ndc_transform = cameras.get_ndc_camera_transform(**kwargs)
  File "/home/bird/bird/Pose/mmhuman3d/mmhuman3d/core/cameras/cameras.py", line 775, in get_ndc_camera_transform
    return super().get_ndc_camera_transform(**kwargs)
  File "/home/bird/anaconda3/envs/mmhuman3d_4090/lib/python3.9/site-packages/pytorch3d/renderer/cameras.py", line 1220, in get_ndc_camera_transform
    screen_to_ndc_transform = get_screen_to_ndc_transform(
  File "/home/bird/anaconda3/envs/mmhuman3d_4090/lib/python3.9/site-packages/pytorch3d/renderer/cameras.py", line 1846, in get_screen_to_ndc_transform
    transform = get_ndc_to_screen_transform(
  File "/home/bird/anaconda3/envs/mmhuman3d_4090/lib/python3.9/site-packages/pytorch3d/transforms/transform3d.py", line 326, in inverse
    i_matrix = self._get_matrix_inverse()
  File "/home/bird/anaconda3/envs/mmhuman3d_4090/lib/python3.9/site-packages/pytorch3d/transforms/transform3d.py", line 296, in _get_matrix_inverse
    return torch.inverse(self._matrix)
RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)`
```

But it works well on my 3090 with the same environment. 
I install PyTorch using: 
```
conda install pytorch==1.9.1 torchvision cudatoolkit=11.1 -c pytorch -c nvidia
```

**Comment by bottler** [comment]
Interesting. So the problem is on a very new GPU. Can you provide enough code to replicate the error? Did you build PyTorch3D from source? 

If you have such a new GPU it makes sense to build from source and use a more recent version of CUDA. I don't know if this combination is meant to work.

**Comment by Vegetebird** [comment]
It seems to be an issue with PyTorch inverse function. 
https://github.com/facebookresearch/pytorch3d/issues/674
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/35993705/208709956-6aff1a25-0c99-4c50-af2e-33635a8ff093.png">

**Comment by Vegetebird** [comment]
It works well on torch1.3 but error on torch1.9 and torch1.7 on my 4090 GPU.

**Comment by bottler** [comment]
Can you stick with a much newer PyTorch? Like 1.13.0?

**Comment by Vegetebird** [comment]
Yeah, I have successfully installed with torch1.13.0+cuda11.6 and torch1.10.1+cuda11.3. Thanks!

**Comment by daddyiel** [comment]
> Yeah, I have successfully installed with torch1.13.0+cuda11.6 and torch1.10.1+cuda11.3. Thanks!

How did you solve the problem

**Comment by MickShen7558** [comment]
> > Yeah, I have successfully installed with torch1.13.0+cuda11.6 and torch1.10.1+cuda11.3. Thanks!
> 
> How did you solve the problem

I solved this by upgrading my torch from 1.11.0 to 1.13.0 (cuda11.7):
`pip install torch==1.13.0 torchvision==0.14.0 torchaudio==0.13.0 --upgrade`

**Comment by hctian713** [comment]
Hi, I have found another solution if you don't wanna change your torch env. You could locate your code and modify it like below
before `torch.inverse(intrins)` 
after `torch.inverse(intrins.cpu()).cuda())`  
from hustvl/MapTR/#111

**Comment by willieChen58** [comment]
> Hi, I have found another solution if you don't wanna change your torch env. You could locate your code and modify it like below before `torch.inverse(intrins)` after `torch.inverse(intrins.cpu()).cuda())` from [hustvl/MapTR#111](https://github.com/hustvl/MapTR/issues/111)
it's incredible !!

**Comment by KnightOfTheMoonlight** [comment]
> Hi, I have found another solution if you don't wanna change your torch env. You could locate your code and modify it like below before `torch.inverse(intrins)` after `torch.inverse(intrins.cpu()).cuda())` from [hustvl/MapTR#111](https://github.com/hustvl/MapTR/issues/111)

Thanks for your ans. I have encountered the same error but with `mm` function. Here is my example change.

```
torch.stack([matrix.mm(b) for b in batch], dim=0)
torch.stack([matrix.cpu().mm(b.cpu()).cuda() for b in batch], dim=0)
```

**Comment by PavanGandhii** [comment]
> Hi, I have found another solution if you don't wanna change your torch env. You could locate your code and modify it like below before `torch.inverse(intrins)` after `torch.inverse(intrins.cpu()).cuda())` from [hustvl/MapTR#111](https://github.com/hustvl/MapTR/issues/111)

how do I locate the code?

**Comment by alexschmidt123** [comment]
> > > Yeah, I have successfully installed with torch1.13.0+cuda11.6 and torch1.10.1+cuda11.3. Thanks!
> > 
> > 
> > How did you solve the problem
> 
> I solved this by upgrading my torch from 1.11.0 to 1.13.0 (cuda11.7): `pip install torch==1.13.0 torchvision==0.14.0 torchaudio==0.13.0 --upgrade`

I met the same problem with pytorch=1.8 cuda=11.1 on 4090 gpu.
I tried to solve it the way you did. but it got a new issue. `RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasStrsmBatched( handle, side, uplo, trans, diag, m, n, alpha, A, lda, B, ldb, batchCount)``

**Comment by AEiouovo** [comment]
> > > Yeah, I have successfully installed with torch1.13.0+cuda11.6 and torch1.10.1+cuda11.3. Thanks!
> > 
> > 
> > How did you solve the problem
> 
> I solved this by upgrading my torch from 1.11.0 to 1.13.0 (cuda11.7): `pip install torch==1.13.0 torchvision==0.14.0 torchaudio==0.13.0 --upgrade`

Thanks a lot for your help!
