### ISSUE TITLE
💥 Bus Error on sample_points_from_meshes() when using MPS device (Apple Silicon)

### ISSUE THREAD

**Issue by chainedcoder** [facebookresearch/pytorch3d#1983]
**Description**
Calling `sample_points_from_meshes()` on an `Meshes` object located on an `MPS` device (Apple Silicon GPU) causes a **hard crash with a "bus error"**, terminating the Python process immediately. The issue does not occur when using the same mesh on a CPU device.

This is likely due to MPS backend incompatibility with low-level CUDA/C++ routines in `sample_points_from_meshes`, which may not be MPS-safe.

---

**System Information**

```
PyTorch Version: PyTorch: 2.7.1
PyTorch3D Version: PyTorch3D: 0.7.8
OS: macOS 15.3.2(Apple Silicon) M1 pro
Python Version: 3.10
Device: MPS (Apple GPU)
```

---

**To Reproduce**

Here’s a complete, minimal, self-contained script to reproduce the issue. It attempts to sample points from a simple cube mesh created directly on the `mps` device.

```python
  import torch
import sys

# --- Pre-computation ---
# We check for PyTorch3D upfront and provide a helpful error message if it's missing.
try:
    from pytorch3d.structures import Meshes
    from pytorch3d.ops import sample_points_from_meshes
except ImportError:
    print("Error: PyTorch3D is not installed.", file=sys.stderr)
    print("Please install it via: `pip install pytorch3d`", file=sys.stderr)
    sys.exit(1)


def create_simple_cube_mesh(device: torch.device) -> Meshes:
    """
    Creates a simple, standard cube mesh directly on the specified device.
    """
    # 8 vertices of the cube
    verts = torch.tensor([
        [-1.0, -1.0, -1.0], [1.0, -1.0, -1.0], [1.0, 1.0, -1.0], [-1.0, 1.0, -1.0],
        [-1.0, -1.0,  1.0], [1.0, -1.0,  1.0], [1.0, 1.0,  1.0], [-1.0, 1.0,  1.0]
    ], dtype=torch.float32, device=device)
    
    # 12 triangular faces of the cube
    faces = torch.tensor([
        [0, 1, 2], [2, 3, 0], [1, 5, 6], [6, 2, 1],
        [7, 6, 5], [5, 4, 7], [4, 0, 3], [3, 7, 4],
        [0, 4, 5], [5, 1, 0], [3, 2, 6], [6, 7, 3]
    ], dtype=torch.int64, device=device)
    
    return Meshes(verts=[verts], faces=[faces])


def main():
    """
    Minimal script to reproduce a bus error when using 
    `sample_points_from_meshes` on an MPS (Apple Silicon GPU) device.
    """
    print(f"PyTorch Version: {torch.__version__}")

    try:
        import pytorch3d
        print(f"PyTorch3D Version: {pytorch3d.__version__}")
    except (ImportError, AttributeError):
        print("PyTorch3D version could not be determined.")
    print("-" * 40)

    # --- Step 1: Verify that an MPS device is available ---
    if not torch.backends.mps.is_available():
        print("This script is intended for testing an MPS-specific bug.")
        print("MPS device not found on this system. Exiting.")
        sys.exit(0)
    
    mps_device = torch.device("mps")
    cpu_device = torch.device("cpu")
    print(f"MPS device found. Will attempt to trigger bug on: {mps_device}")
    
    # --- Step 2: Demonstrates the successful workaround on CPU ---
    # This proves that the core logic and mesh structure are valid.
    print("\n--- Test 1: Sampling on CPU (Expected to Succeed) ---")
    try:
        cpu_mesh = create_simple_cube_mesh(device=cpu_device)
        print("  - Created a simple cube mesh on CPU.")
        sampled_points_cpu = sample_points_from_meshes(cpu_mesh, num_samples=1000)
        print(f"✅ SUCCESS: Sampled {sampled_points_cpu.shape[1]} points successfully on CPU.")
    except Exception as e:
        print(f"❌ UNEXPECTED FAILURE on CPU: {e}")

    # --- Step 3: Reproduce the bus error by running on MPS ---
    print("\n--- Test 2: Sampling on MPS (Expected to crash with a 'bus error') ---")
    print("  - Creating a simple cube mesh directly on MPS device...")
    mps_mesh = create_simple_cube_mesh(device=mps_device)
    print("  - Mesh created successfully on MPS.")
    print("  - Now calling `sample_points_from_meshes` on the MPS mesh...")
    print("\n  >>> If the bug is present, the script will crash with a 'bus error' now. <<<")
    print("  >>> You should NOT see a 'SUCCESS' message for this test.         <<<")
    sys.stdout.flush()

    try:
        # This is the specific function call that is expected to crash the script.
        sampled_points_mps = sample_points_from_meshes(mps_mesh, num_samples=1000)
        
        # This part should not be reached if the bug is present.
        print(f"\n✅ UNEXPECTED SUCCESS: If you see this, the bug may be fixed or is environment-dependent.")
        print(f"   It appears sampling {sampled_points_mps.shape[1]} points on MPS succeeded without a crash.")
    except Exception as e:
        print(f"\n❌ FAILED with a Python exception (this is unexpected): {e}")

if __name__ == "__main__":
    main()

```

---

**Steps:**

1. Ensure you’re running on an Apple Silicon Mac with MPS available.
2. Install PyTorch with MPS support and PyTorch3D.
3. Run the script.
4. Observe that:

   * Sampling on CPU works fine.
   * Sampling on MPS results in a **"bus error"** with no Python exception.

---

**Expected Behavior**
`sample_points_from_meshes()` should either:

* Work normally on MPS (preferred), or
* Gracefully raise a Python exception or explicitly indicate unsupported functionality on MPS, rather than crashing with a bus error.

---

**Actual Behavior**
When using an MPS device:

* The call to `sample_points_from_meshes()` causes a system-level **bus error**, terminating the interpreter.

---

**Additional Notes**

* This is reproducible on a minimal cube mesh (no external file I/O).
* This strongly suggests a lower-level incompatibility between the MPS backend and internal operations used by `sample_points_from_meshes()`.

**Comment by bottler** [comment]
I suspect that to avoid this, we need more checking for other devices in basically every compiled function. The regular pattern is like https://github.com/facebookresearch/pytorch3d/blob/main/pytorch3d/csrc/face_areas_normals/face_areas_normals.h#L54-L63 (which is a function used by sample_points_from_meshes).

The CPU path is taken if the inputs are non-cuda. But it should also check the inputs are actually on CPU.

**Comment by melvinhe** [comment]
Thanks for outlining the issue. I'm currently working on a fix internally to address the compatibility of MPS devices with the sample_points_from_meshes function. Our goal is to ensure that the function either operates correctly on MPS or gracefully handles unsupported scenarios without causing a crash. I'll keep you updated on the progress and ensure our tests and documentation reflect this new preferred behavior.

**Comment by melvinhe** [comment]
Resolved internally. Fixes Apple Silicon MPS hard crashes with on-CPU checks iff inputs are non-cuda.

**Comment by chainedcoder** [comment]
This is great news. Thank you for the update and the fix, @melvinhe It's great to see that the issue is resolved internally by adding the device checks. My thanks to @bottler  as well for pinpointing the likely cause so early on.

**Comment by mshooter** [comment]
@melvinhe would be great if you could push the solution ! :)

**Comment by melvinhe** [comment]
@mshooter This issue has been resolved. I've pushed the fixing changes through previous commits through our internal system at Meta, which might not appear directly linked in this issue thread, but are implemented. 

For any new or related bugs or feature requests that arise, please create a new issue accordingly. Thank you.
