### ISSUE TITLE
Installation Issue After Following Installation Instructions

### ISSUE THREAD

**Issue by fishyai** [facebookresearch/pytorch3d#235]
If you do not know the root cause of the problem / bug, and wish someone to help you, please
post according to this template:

## 🐛 Bugs / Unexpected behaviors
Hi all,

I've followed the installation instructions on the installation page, but the stable version of the library doesn't seem to be compatible with Python3.8 (which is the recommended version in the installation document). 

Additionally, there seems to be a cuda error in building (although I'm not sure if that's my system or from the installation instructions).

NOTE: Please look at the existing list of Issues tagged with the label ['bug`](https://github.com/facebookresearch/pytorch3d/issues?q=label%3Abug). **Only open a new issue if this bug has not already been reported. If an issue already exists, please comment there instead.**.

## Instructions To Reproduce the Issue:

Please include the following (depending on what the issue is):

1. Any changes you made (`git diff`) or code you wrote: None
2. The exact command(s) you ran: I followed the installation instructions here: https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md

```
> conda create -n pytorch3d python=3.8
> conda activate pytorch3d
> conda install -c pytorch pytorch torchvision cudatoolkit=10.2
> conda install -c conda-forge -c fvcore fvcore
> conda install jupyter
> pip install scikit-image matplotlib imageio
> pip install black isort flake8 flake8-bugbear flake8-comprehensions
> conda install pytorch3d -c pytorch3d
```

FWIW, I found this to be an issue with both the nightly and the stable build.

3. What you observed (including the full logs):

I got these errors:
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pytorch3d -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2

```

**Comment by fishyai** [comment]
Also, I see other people have had this issue with the Cuda driver when upgrading packages from 3.7 to 3.8 in Conda. It seems like it's not an issue with my system but with the metadata. Here is an example of how someone fixed it: https://github.com/KevinMusgrave/pytorch-metric-learning/issues/55#issuecomment-629698723

**Comment by bottler** [comment]
I don't think that's the problem: you aren't trying to build the conda packages, just use them. Can you paste the output of `conda list` and `conda info` please? Thanks

**Comment by fishyai** [comment]
Thanks @bottler.

```
> conda list
# packages in environment at /home/fishy/anaconda3/envs/pytorch3d:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
appdirs                   1.4.4                    pypi_0    pypi
attrs                     19.3.0                     py_0  
backcall                  0.1.0                    py38_0  
black                     19.10b0                  pypi_0    pypi
blas                      1.0                         mkl  
bleach                    3.1.4                      py_0  
ca-certificates           2020.1.1                      0  
certifi                   2020.4.5.1               py38_0  
click                     7.1.2                    pypi_0    pypi
cudatoolkit               10.2.89              hfd86e86_1  
cycler                    0.10.0                   pypi_0    pypi
dbus                      1.13.14              hb2f20db_0  
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.6.0                      py_0  
entrypoints               0.3                      py38_0  
expat                     2.2.6                he6710b0_0  
flake8                    3.8.3                    pypi_0    pypi
flake8-bugbear            20.1.4                   pypi_0    pypi
flake8-comprehensions     3.2.3                    pypi_0    pypi
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_1  
glib                      2.63.1               h3eb4bd4_1  
gmp                       6.1.2                h6c8ec71_1  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb31296c_0  
icu                       58.2                 he6710b0_3  
imageio                   2.8.0                    pypi_0    pypi
importlib-metadata        1.6.0                    py38_0  
importlib_metadata        1.6.0                         0  
intel-openmp              2020.1                      217  
ipykernel                 5.1.4            py38h39e3cac_0  
ipython                   7.13.0           py38h5ca1d4c_0  
ipython_genutils          0.2.0                    py38_0  
ipywidgets                7.5.1                      py_0  
isort                     4.3.21                   pypi_0    pypi
jedi                      0.17.0                   py38_0  
jinja2                    2.11.2                     py_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                    py38_0  
jupyter                   1.0.0                    py38_7  
jupyter_client            6.1.3                      py_0  
jupyter_console           6.1.0                      py_0  
jupyter_core              4.6.3                    py38_0  
kiwisolver                1.2.0                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.3                  he6710b0_1  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.10               he19cac6_1  
lz4-c                     1.9.2                he6710b0_0  
markupsafe                1.1.1            py38h7b6447c_0  
matplotlib                3.2.1                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4           py38h7b6447c_1000  
mkl                       2020.1                      217  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.0.15           py38ha843d7b_0  
mkl_random                1.1.1            py38h0573a6f_0  
nbconvert                 5.6.1                    py38_0  
nbformat                  5.0.6                      py_0  
ncurses                   6.2                  he6710b0_1  
networkx                  2.4                      pypi_0    pypi
ninja                     1.9.0            py38hfd86e86_0  
notebook                  6.0.3                    py38_0  
numpy                     1.18.1           py38h4f9e942_0  
numpy-base                1.18.1           py38hde5b4d6_1  
olefile                   0.46                       py_0  
openssl                   1.1.1g               h7b6447c_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py38_1  
parso                     0.7.0                      py_0  
pathspec                  0.8.0                    pypi_0    pypi
pcre                      8.43                 he6710b0_0  
pexpect                   4.8.0                    py38_0  
pickleshare               0.7.5                 py38_1000  
pillow                    7.1.2            py38hb39fc2d_0  
pip                       20.0.2                   py38_3  
prometheus_client         0.7.1                      py_0  
prompt-toolkit            3.0.5                      py_0  
prompt_toolkit            3.0.5                         0  
ptyprocess                0.6.0                    py38_0  
pycodestyle               2.6.0                    pypi_0    pypi
pyflakes                  2.2.0                    pypi_0    pypi
pygments                  2.6.1                      py_0  
pyparsing                 2.4.7                    pypi_0    pypi
pyqt                      5.9.2            py38h05f1152_4  
pyrsistent                0.16.0           py38h7b6447c_0  
python                    3.8.3                hcff3b4d_0  
python-dateutil           2.8.1                    pypi_0    pypi
pytorch                   1.5.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
pywavelets                1.1.1                    pypi_0    pypi
pyzmq                     18.1.1           py38he6710b0_0  
qt                        5.9.7                h5867ecd_1  
qtconsole                 4.7.4                      py_0  
qtpy                      1.9.0                      py_0  
readline                  8.0                  h7b6447c_0  
regex                     2020.6.8                 pypi_0    pypi
scikit-image              0.17.2                   pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
send2trash                1.5.0                    py38_0  
setuptools                47.1.1                   py38_0  
sip                       4.19.13          py38he6710b0_0  
six                       1.15.0                     py_0  
sqlite                    3.31.1               h62c20be_1  
terminado                 0.8.3                    py38_0  
testpath                  0.4.4                      py_0  
tifffile                  2020.6.3                 pypi_0    pypi
tk                        8.6.8                hbc83047_0  
toml                      0.10.1                   pypi_0    pypi
torchvision               0.6.0                py38_cu102    pytorch
tornado                   6.0.4            py38h7b6447c_1  
traitlets                 4.3.3                    py38_0  
typed-ast                 1.4.1                    pypi_0    pypi
wcwidth                   0.1.9                      py_0  
webencodings              0.5.1                    py38_1  
wheel                     0.34.2                   py38_0  
widgetsnbextension        3.5.1                    py38_0  
xz                        5.2.5                h7b6447c_0  
zeromq                    4.3.1                he6710b0_3  
zipp                      3.1.0                      py_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.4                h0b5b093_3  
```

```
> conda info

     active environment : pytorch3d
    active env location : /home/fishy/anaconda3/envs/pytorch3d
            shell level : 1
       user config file : /home/fishy/.condarc
 populated config files : /home/fishy/.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.2
                          __glibc=2.27
       base environment : /home/fishy/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/fishy/anaconda3/pkgs
                          /home/fishy/.conda/pkgs
       envs directories : /home/fishy/anaconda3/envs
                          /home/fishy/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.6 Linux/5.3.0-53-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by bottler** [comment]
I just ran almost the same sequence of commands as you on basically the same platform (linux64, conda 4.8.3) and it worked. It seems like in your case the fvcore installation failed. You don't have fvcore or its dependency `yacs`  in your environment. Do you get an error from `conda install -c conda-forge -c fvcore fvcore`?

**Comment by fishyai** [comment]
I tried rerunning the command and it worked. I guess the installation of that package must have failed and caused the pytorch3d installation to fail. **facepalm**

Thanks for your help!
