### ISSUE TITLE
Bug: RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by adelekuzmiakova** [facebookresearch/pytorch3d#518]
## 🐛 Bugs / Unexpected behaviors

Hello,

When I run the code to render multiple texture files per mesh, I get a runtime error `RuntimeError: CUDA error: device-side assert triggered`. 

I run the following code: 
```
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
import torch
import matplotlib.pyplot as plt
import matplotlib
from skimage.io import imread
from io_utils import return_filenames

from pytorch3d.io import load_objs_as_meshes, load_obj
from pytorch3d.structures import Meshes
from pytorch3d.renderer import (
    look_at_view_transform,
    FoVPerspectiveCameras, 
    PointLights, 
    DirectionalLights, 
    Materials, 
    RasterizationSettings, 
    MeshRenderer, 
    MeshRasterizer,  
    SoftPhongShader,
    TexturesUV,
    TexturesAtlas
)

# Set the device
if torch.cuda.is_available():
    device = torch.device("cuda:0")
    torch.cuda.set_device(device)
else:
    device = torch.device("cpu")

print(device)

# Input parameters:
rendered_image_size = 1024  
camera_distance = 20
elevation = 0
azimuth_list = [0, 30, 60, 90, 120, 150, 180]

obj_filename = "data/textured-scans/1553_KX16_OptiTexAdamF3_ateamleft_out.obj"


def setup_renderer(image_size, camera_distance, elevation, azimuth):

    print("Image size: " + str(image_size) + ", elevation: " + str(elevation) + ", azimuth: " + str(azimuth))
    raster_settings = RasterizationSettings(
    image_size=rendered_image_size, 
    faces_per_pixel=1,)

    # Set up field-of-view rotation and translation matrices
    R, T = look_at_view_transform(camera_distance, elevation, azimuth) 
    cameras = FoVPerspectiveCameras(device=device, R=R, T=T)

    lights = PointLights(device=device, location=[[1000.0, 1000.0, -500.0]])
    
    # Set up MeshRenderer class
    renderer = MeshRenderer(
    rasterizer=MeshRasterizer(
        cameras=cameras, 
        raster_settings=raster_settings
    ),
    shader=SoftPhongShader(
        device=device, 
        cameras=cameras,)
    )
    return renderer
    

def setup_mesh(obj_filename):
     
    print("Rendering " + str(obj_filename))
    
    verts, faces, aux = load_obj(
    obj_filename,
    device=device,
    load_textures=True,
    create_texture_atlas=True,
    texture_atlas_size=4,
    texture_wrap="repeat",
    #texture_wrap= "clamp"
    #texture_wrap= None,
     )

    # Create Meshes class using vertices and faces from the .obj file. Uses TexturesAtlas 
    # method to store heterogeneous textures per mesh
    atlas = aux.texture_atlas
    mesh = Meshes(
    verts=[verts],
    faces=[faces.verts_idx],
    textures=TexturesAtlas(atlas=[atlas]),)
    return mesh


def render_mesh(mesh, renderer):

    image = renderer(mesh)
    if device == torch.device("cuda:0"):
        im_array = image[0, ..., :3].cpu().detach().numpy()
    else:
        im_array = image[0, ..., :3].numpy()
    return im_array


for azimuth_value in azimuth_list:
    mesh = setup_mesh(obj_filename)
    renderer = setup_renderer(rendered_image_size, camera_distance, elevation, azimuth_value)
    im_array = render_mesh(mesh, renderer)
```
The error log I observe:

```


Rendering data/textured-scans/1553_KX16_OptiTexAdamF3_ateamleft_out.obj

/home/ubuntu/.local/lib/python3.6/site-packages/pytorch3d/io/mtl_io.py:95: UserWarning: Texture UV coordinates outside the range [0, 1].                 The integer part will be ignored to form a repeating pattern.
  warnings.warn(msg)

Image size: 1024, elevation: 0, azimuth: 0
Rendering data/textured-scans/1553_KX16_OptiTexAdamF3_ateamleft_out.obj
Image size: 1024, elevation: 0, azimuth: 30
Rendering data/textured-scans/1553_KX16_OptiTexAdamF3_ateamleft_out.obj
Image size: 1024, elevation: 0, azimuth: 60
Rendering data/textured-scans/1553_KX16_OptiTexAdamF3_ateamleft_out.obj
Image size: 1024, elevation: 0, azimuth: 90

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-a36317e66f82> in <module>
      2     mesh = setup_mesh(obj_filename)
      3     renderer = setup_renderer(rendered_image_size, camera_distance, elevation, azimuth_value)
----> 4     im_array = render_mesh(mesh, renderer)
      5     plt.figure(figsize=(10, 10))
      6     plt.imshow(im_array)

<ipython-input-3-a5f51c374a6a> in render_mesh(mesh, renderer)
    108 
    109     """
--> 110     image = renderer(mesh)
    111     if device == torch.device("cuda:0"):
    112         im_array = image[0, ..., :3].cpu().detach().numpy()

~/.local/lib/python3.6/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/.local/lib/python3.6/site-packages/pytorch3d/renderer/mesh/renderer.py in forward(self, meshes_world, **kwargs)
     53         """
     54         fragments = self.rasterizer(meshes_world, **kwargs)
---> 55         images = self.shader(fragments, meshes_world, **kwargs)
     56 
     57         return images

~/.local/lib/python3.6/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/.local/lib/python3.6/site-packages/pytorch3d/renderer/mesh/shader.py in forward(self, fragments, meshes, **kwargs)
    118             raise ValueError(msg)
    119 
--> 120         texels = meshes.sample_textures(fragments)
    121         lights = kwargs.get("lights", self.lights)
    122         materials = kwargs.get("materials", self.materials)

~/.local/lib/python3.6/site-packages/pytorch3d/structures/meshes.py in sample_textures(self, fragments)
   1493             # the vertex attributes across the face.
   1494             return self.textures.sample_textures(
-> 1495                 fragments, faces_packed=self.faces_packed()
   1496             )
   1497         else:

~/.local/lib/python3.6/site-packages/pytorch3d/renderer/mesh/textures.py in sample_textures(self, fragments, **kwargs)
    514         w_y = torch.where(below_diag, w_y, (R - 1 - w_y))
    515 
--> 516         texels = atlas_packed[pix_to_face, w_y, w_x]
    517         texels = texels * (pix_to_face >= 0)[..., None].float()
    518 

RuntimeError: CUDA error: device-side assert triggered

```
**Link to the [code](https://github.com/adelekuzmiakova/render-mesh-pytorch3d/blob/main/render-meshes_render-meshes-multiple-textures-v2.ipynb), [data](https://github.com/adelekuzmiakova/render-mesh-pytorch3d/tree/main/data/textured-scans)**

The code breaks down when azimuth value == 90, otherwise it runs without any issues. I've looked at your documentation regarding [barycentric coordinates](https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/renderer/mesh/textures.py) but I'm not really sure what exactly should I change. Could you please shed some light on what exactly the issue might be? If so, that'd be fantastic!

Also, here's the list of packages in case that might be helpful:

```


Package                       Version
----------------------------- -------------------
alabaster                     0.7.12
appdirs                       1.4.3
argon2-cffi                   20.1.0
asn1crypto                    0.24.0
astroid                       2.4.2
async-generator               1.10
attr                          0.3.1
attrs                         20.3.0
Automat                       0.6.0
awscli                        1.18.181
Babel                         2.9.0
backcall                      0.2.0
bleach                        3.2.1
blinker                       1.4
bokeh                         2.2.3
boto                          2.49.0
boto3                         1.16.21
botocore                      1.19.21
cached-property               1.5.2
certifi                       2020.11.8
cffi                          1.14.3
chardet                       3.0.4
click                         6.7
cloud-init                    20.4
cmake                         3.18.4.post1
colorama                      0.4.3
command-not-found             0.3
configobj                     5.0.6
constantly                    15.1.0
coremltools                   4.0
cpplint                       1.5.4
cryptography                  3.2.1
cycler                        0.10.0
decorator                     4.4.2
defusedxml                    0.6.0
distro-info                   0.18ubuntu0.18.04.1
docutils                      0.15.2
ec2-hibinit-agent             1.0.0
entrypoints                   0.3
environment-kernels           1.1.1
future                        0.18.2
fvcore                        0.1.2.post20201218
gcc7                          0.0.7
graphviz                      0.15
h5py                          3.1.0
hibagent                      1.0.1
httplib2                      0.9.2
hyperlink                     17.3.1
idna                          2.10
imageio                       2.9.0
imagesize                     1.2.0
importlib-metadata            2.0.0
incremental                   16.10.1
iopath                        0.1.2
ipykernel                     5.3.4
ipython                       7.16.1
ipython-genutils              0.2.0
ipywidgets                    7.5.1
isort                         5.6.4
jedi                          0.17.2
Jinja2                        2.11.2
jmespath                      0.10.0
joblib                        0.17.0
jsonpatch                     1.16
jsonpointer                   1.10
jsonschema                    3.2.0
jupyter                       1.0.0
jupyter-client                6.1.7
jupyter-console               6.2.0
jupyter-core                  4.7.0
jupyterlab-pygments           0.1.2
keyring                       10.6.0
keyrings.alt                  3.0
kiwisolver                    1.3.1
language-selector             0.1
lazy-object-proxy             1.4.3
MarkupSafe                    1.1.1
matplotlib                    3.3.3
mccabe                        0.6.1
mistune                       0.8.4
mpmath                        1.1.0
nbclient                      0.5.1
nbconvert                     6.0.7
nbformat                      5.0.8
nest-asyncio                  1.4.3
netifaces                     0.10.4
networkx                      2.5
nose                          1.3.7
notebook                      6.1.5
numpy                         1.19.4
nvidia-ml-py                  10.418.84
oauthlib                      2.0.6
opencv-python                 4.4.0.46
packaging                     20.4
PAM                           0.4.2
pandas                        1.1.4
pandocfilters                 1.4.3
parso                         0.7.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.0.1
pip                           20.3.3
plotly                        4.14.1
portalocker                   2.0.0
prometheus-client             0.9.0
prompt-toolkit                3.0.8
protobuf                      3.14.0
ptyprocess                    0.6.0
pyasn1                        0.4.8
pyasn1-modules                0.2.1
pycparser                     2.20
pycrypto                      2.6.1
pydot                         1.4.1
pygal                         2.4.0
Pygments                      2.7.2
pygobject                     3.26.1
PyJWT                         1.5.3
pylint                        2.6.0
pyOpenSSL                     17.5.0
pyparsing                     2.4.7
pyrsistent                    0.17.3
pyserial                      3.4
python-apt                    1.6.5+ubuntu0.5
python-dateutil               2.8.1
python-debian                 0.1.32
pytorch3d                     0.3.0
pytz                          2020.4
PyWavefront                   1.3.3
PyWavelets                    1.1.1
pyxdg                         0.25
PyYAML                        5.3.1
pyzmq                         20.0.0
qtconsole                     4.7.7
QtPy                          1.9.0
requests                      2.25.0
requests-unixsocket           0.1.5
retrying                      1.3.3
rsa                           4.5
s3transfer                    0.3.3
scikit-image                  0.17.2
scikit-learn                  0.23.2
scipy                         1.5.4
seaborn                       0.11.0
SecretStorage                 2.3.1
Send2Trash                    1.5.0
service-identity              16.0.0
setuptools                    50.3.2
simplegeneric                 0.8.1
six                           1.15.0
snowballstemmer               2.0.0
Sphinx                        3.3.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
ssh-import-id                 5.7
sympy                         1.6.2
systemd-python                234
tabulate                      0.8.7
termcolor                     1.1.0
terminado                     0.9.1
testpath                      0.4.4
threadpoolctl                 2.1.0
tifffile                      2020.9.3
toml                          0.10.2
torch                         1.6.0
torchvision                   0.7.0
tornado                       6.1
tqdm                          4.52.0
traitlets                     4.3.3
Twisted                       17.9.0
typed-ast                     1.4.1
typing-extensions             3.7.4.3
ufw                           0.36
unattended-upgrades           0.1
urllib3                       1.26.2
virtualenv                    15.1.0
wavefront-reader              0.2.2
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.35.1
widgetsnbextension            3.5.1
wrapt                         1.12.1
yacs                          0.1.8
zipp                          3.4.0
zope.interface                4.3.2

```

**Comment by nikhilaravi** [comment]
I see you're installing PyTorch3D from the conda package. There was an issue with the texture sampling for the texture atlas type where in some cases the barycentric coordinates are exactly 1.0 and they map to the x/y coordinate of R (the texture atlas size). In this case the texture atlas sampling fails because the values are taken from a discrete grid which has values in the range [0, R-1]. 

We have fixed this issue in the master branch of the code (https://github.com/facebookresearch/pytorch3d/commit/01759d8ffb4899de1157398e4052f76a13c56527) but have not published a bug fix conda package. You can install PyTorch3D from GitHub (following the [installation instructions](https://github.com/facebookresearch/pytorch3d/blob/master/INSTALL.md)) to resolve the issue.

**Comment by adelekuzmiakova** [comment]
Thanks! Yes, I installed PyTorch3D from source using 

`pip install "git+https://github.com/facebookresearch/pytorch3d.git"`

and it worked!
