### ISSUE TITLE
How do I use torch.jit.trace with Pytorch3d?

### ISSUE THREAD

**Issue by vegetable09** [facebookresearch/pytorch3d#581]
I want to use torch.jit.trace to export pytorch3d to an 
and I refered to the cow example. However, I meet the problem that torch.jit.trace only support Tensor and int as parameters. detail Error message is following:
```
RuntimeError: Tracer cannot infer type of (<pytorch3d.structures.meshes.Meshes object at 0x7f264f75fdc0>,)
:Only tensors and (possibly nested) tuples of tensors, lists, or dictsare supported as inputs or outputs of traced functions, but instead got value of type Meshes.
```
And my code is following, the only difference between my code and the original cow example is I used torch.jit.trace to trace the input through the Render
```
import os
import sys
import torch
import warnings
import matplotlib.pyplot as plt
from skimage.io import imread
# Util function for loading meshes
import pytorch3d
from pytorch3d.io import load_objs_as_meshes, load_obj
# Data structures and functions for rendering
from pytorch3d.structures import Meshes
from pytorch3d.vis.plotly_vis import AxisArgs, plot_batch_individually, plot_scene
from pytorch3d.vis.texture_vis import texturesuv_image_matplotlib
from pytorch3d.renderer import (
    look_at_view_transform,
    FoVPerspectiveCameras, 
    PointLights, 
    DirectionalLights, 
    Materials, 
    RasterizationSettings, 
    MeshRenderer, 
    MeshRasterizer,  
    SoftPhongShader,
    TexturesUV,
    TexturesVertex
)
# add path for demo utils functions 
import sys
import os
sys.path.append(os.path.abspath(''))
from plot_image_grid import image_grid
# from utils import image_grid
# Setup
if torch.cuda.is_available():
    device = torch.device("cuda:0")
    torch.cuda.set_device(device)
else:
    warnings.warn("gpu NOT found! cpu is used")
    device = torch.device("cpu")
# Set paths
DATA_DIR = "./data"
obj_filename = os.path.join(DATA_DIR, "cow_mesh/cow.obj")
import time
# Load obj file
start = time.perf_counter()
mesh = load_objs_as_meshes([obj_filename], device=device)
end = time.perf_counter()
print(f"load objs cost: {end - start:.3f} s")
# Initialize a camera.
R, T = look_at_view_transform(15, 15, 15)
cameras = FoVPerspectiveCameras(device=device, R=R, T=T) # cameras是module
raster_settings = RasterizationSettings( 
    image_size=512, 
    blur_radius=0.0, 
    faces_per_pixel=1, 
)
lights = PointLights(device=device, location=[[0.0, 0.0, -3.0]]) # Module
# jit
renderer = MeshRenderer(
    rasterizer=MeshRasterizer(  #Module
        cameras=cameras, 
        raster_settings=raster_settings
    ),
    shader=SoftPhongShader(  # Module
        device=device, 
        cameras=cameras,
        lights=lights
    )
)

images = renderer(mesh)

traced_script_module = torch.jit.trace(renderer, (mesh))
# traced_script_module = torch.jit.trace(model, (im))
torch.jit.save(traced_script_module, "render.pt")
jit_model = torch.jit.load("render.pt")
jit_output = jit_model(mesh)
torch.allclose(images, jit_output)

plt.figure(figsize=(10, 10))
plt.imshow(images[0, ..., :3].cpu().numpy())
plt.grid("off");
plt.axis("off");
plt.savefig("test.png")
```

**Comment by bottler** [comment]
PyTorch3D is not currently torchscriptable. I think making the renderer torchscriptable would be quite a lot of work. It would be interesting to know what your motivation is for wanting it. Would you be happy to help out?

**Comment by vegetable09** [comment]
@bottler Thanks for rapid reply. My motivation is to use pytorch3d in prd environment as a render service. For my company, onnx and jit model are both supported.

My env is pytorch 1.5.0, cuda10.2, pytorch3d 0.4.0, onnxruntime 1.3.1

At First, I try export pytorch3d to onnx, it doesn't works. After add @symbolic to the Rasterizer (inheriate torch.autograd.Function), it can export to onnx. HOWEVER, onnxruntime cannot load and run it. And the prd env using onnxruntime to infer the onnx model.

Then, I turn to jit, as the pytorch tutorial said, tracing failed due to  the Rasterizer (inheriate torch.autograd.Function) again.

As far as I see, there maybe a way to work it out. 
Using the libtorch extension to wrapper the Rasterizer as a .so file as https://github.com/chrischoy/pytorch-custom-cuda-tutorial do, and load it in pytorch, then export to jit.

**Comment by vegetable09** [comment]
I also notice that pytorch3d provide a so called rasterize_meshes_python() in https://github.com/facebookresearch/pytorch3d/blob/master/pytorch3d/renderer/mesh/rasterize_meshes.py, however, it need 10 hours to render a obj file with 40,000 faces to a 64x64 rgb image.

**Comment by bottler** [comment]
Our rasterizer is a custom C++/cuda function exposed via pybind11. You can't script such a thing. That's why you are getting the error. The interface would need to be changed to make it a torchscript op - see [here](https://pytorch.org/tutorials/advanced/torch_script_custom_ops.html) - for how. I think there also might another more recent way to do this called `torchbind` or something. Updating this would be easy.

But the rasterization step is just the first stage in the renderer, which is mostly in Python. Fixing the rest is what I imagine will be difficult. The Python rasterizer you mention isn't the solution, but by switching to it and trying to render a tiny mesh you might get an idea of the errors you get from trying to trace the rest of the renderer.

**Comment by vegetable09** [comment]
Thanks for your advice. I realize it's really a lot of work to script it.
I found a solution:
1. use pytorch3d to train a 3d reconstruction model
2. when infer, I use OpenGL to render the 3d data to avoid script the renderer.
