### ISSUE TITLE
libcudart.so.11

### ISSUE THREAD

**Issue by fisakhan** [facebookresearch/pytorch3d#709]
## 🐛 Bugs / Unexpected behaviors
It looks like pytorch3d creates a problem with version of the cuda  
I have cuda 11 and get the following error. What should I do?
```
File "/home/tface/.virtualenvs/torch/lib/python3.6/site-packages/pytorch3d/renderer/blending.py", line 9, in <module>
    from pytorch3d import _C
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory
```
Info about environment:

```
sys.platform: linux
Python: 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1060
CUDA_HOME: /usr/local/cuda-11.0
NVCC: Build cuda_11.0_bu.TC445_37.28845127_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.4.0
MMCV: 1.3.3
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.0
MMDetection: 2.7.0+f5c8dc6

```

**Comment by bottler** [comment]
The PyTorch3D you have was built with CUDA 10.1, but you are using CUDA 11.0. If you want more help, please explain how you installed.

**Comment by fisakhan** [comment]
I was executing using https://github.com/ascust/3DMM-Fitting-Pytorch and by executing python3 fit.py --img data/000002.jpg encountered the following error:

[cuda available ?  True
Traceback (most recent call last):
  File "fit.py", line 10, in <module>
    from core.models import ReconModel
  File "/home/tface/Projects/torch/3DMM-Fitting-Pytorch/core/models.py", line 5, in <module>
    from pytorch3d.renderer import (
  File "/home/tface/.virtualenvs/torch/lib/python3.6/site-packages/pytorch3d/renderer/__init__.py", line 3, in <module>
    from .blending import (
  File "/home/tface/.virtualenvs/torch/lib/python3.6/site-packages/pytorch3d/renderer/blending.py", line 9, in <module>
    from pytorch3d import _C
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory](url)

**Comment by bottler** [comment]
The installation instructions on that page begin with 
> **pytorch3d** It might require a specific version of Pytorch to make pytorch3d run succussfully on gpus, please follow the official instructions.

So they are deferring to our installation procedure, which is good. Can you explain what you did to install PyTorch3D? It hasn't worked.

**Comment by fisakhan** [comment]
I used `pip install pytorch3d` and with `pip freeze` i can see `pytorch3d==0.3.0`.

**Comment by bottler** [comment]
This won't work with CUDA 11.0. Installing prebuilt PyTorch3D requires care to match the versions of CUDA and PyTorch. With version 0.4.0, we stopped putting binary packages on PyPI for Linux. 0.4.0 is also the first version where we supplied builds for CUDA 11.0.

Please follow the instructions in [INSTALL.md](https://github.com/facebookresearch/pytorch3d/blob/v0.4.0/INSTALL.md) (which no longer mention using PyPI for Linux). I recommend either installing from source or using conda. Safest in a new environment / virtualenv.

**Comment by fisakhan** [comment]
Thanks @bottler. It is working now.
