### ISSUE TITLE
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by HelloMaroon** [facebookresearch/pytorch3d#757]
I met the same problem with them.
https://github.com/facebookresearch/pytorch3d/issues/688
https://github.com/facebookresearch/pytorch3d/issues/709

Before I met this question, I installed the pytorch3d with these codes:
`conda create -n myenv python=3.8`
`conda activate myenv`
`conda install -c pytorch pytorch=1.7.1 torchvision cudatoolkit=10.2`
`conda install -c fvcore -c iopath -c conda-forge fvcore iopath`

`conda install pytorch3d -c pytorch3d`
and everything is great.

Then I found that I can't reach to the Network and I found the driver Cuda version is 10.0:
NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0
So in order to satisfy the Dalma, I create a new environment with cuda version less than 10.0:

`conda create -n myenv python=3.8`
`conda activate myenv`
`conda install -c pytorch pytorch=1.7.1 torchvision cudatoolkit=9.2`
`conda install -c fvcore -c iopath -c conda-forge fvcore iopath`

However, when I try to install the pytorch3d as before, the result is:
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

And finally I can't install it successfully.

After that, I installed it with other way. Forexample:
1. pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu92_pyt171/download.html
2. pip install pytorch3d

However, no matter which way I use, the result is still:
`ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory`
And the channel is pypi instead of pytorch3d

So I wonder we can't use it for Cuda less than 10.0?

**Comment by bottler** [comment]
The method with conda and cuda 9.2 should have worked. Let's focus on that. Can you try the same again?
```
conda create -n myenv1 python=3.8
conda activate myenv1
conda install -c pytorch pytorch=1.7.1 torchvision cudatoolkit=9.2
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
```
Then try
```
conda install pytorch3d -c pytorch3d
```
again.
If it fails, can you paste the error you see here, as well as the output of `conda info` and `conda list`?

**Comment by HelloMaroon** [comment]
After I set the new environment, I try to install the pytorch3d. 
After several minutes, it told me that 'Your installed version is: 2.17'
![image](https://user-images.githubusercontent.com/66470047/125496882-a9e0bbdb-9e33-461c-b872-41ada581a3c3.png)

Then this is the 'conda list' result. There's no pytorch3d!
![image](https://user-images.githubusercontent.com/66470047/125497023-6e7e58e7-3718-4a85-b4bf-c626d16fa2b9.png)

'conda info':
![image](https://user-images.githubusercontent.com/66470047/125497164-7f6855f1-19ab-408a-bcc7-494782da695f.png)

Then I submit my job again.
![image](https://user-images.githubusercontent.com/66470047/125497461-9e664756-8d35-490d-a40e-c5ea30b1ecc0.png)

This is the result. It's worse than that when I use pip to install.
![image](https://user-images.githubusercontent.com/66470047/125497562-4306aa6f-c6f7-4e53-9087-4b6dd2fbb92a.png)

**Comment by bottler** [comment]
Can you scroll down the `conda list` output and paste any more? I can't see torchvision, for example.

**Comment by HelloMaroon** [comment]
![Uploading image.png…]()

**Comment by HelloMaroon** [comment]
![image](https://user-images.githubusercontent.com/66470047/125498799-1452ed21-7c73-426b-a06d-e65c83fb56ad.png)

**Comment by bottler** [comment]
Sorry, I just realised. There is no conda package for cuda 9.2 with PyTorch 1.7.1. The combinations built for the latest release are [shown here](https://github.com/facebookresearch/pytorch3d/blob/v0.4.0/.circleci/regenerate.py#L17--L24). There is one for PyTorch **1.6.0** with cuda 9.2.

**Comment by HelloMaroon** [comment]
OK, I'll try this again in a new environment. After that, I'll show the new result.

**Comment by HelloMaroon** [comment]
Thanks a lot!  My problem is solved. Now I installed the pytorch3d 0.4.0 with Cuda 9.2 and the bug didn't happen anymore.
