### ISSUE TITLE
When rendering 3D meshes - CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by hamid162** [facebookresearch/pytorch3d#766]
Hello, 

Thanks for the great library. I've got an issue where whenever I try to use a CUDA device for rendering meshes using pytorch3d.renderer.MeshRenderer, I get the following error " CUDA error: no kernel image is available for execution on the device". When I set my device to "cpu", the error goes away, but it then becomes very slow since its running on the cpu.  I am using Google Colab for all my work.

When I run one of the tutorials provided for the Pytorch3d renders, such as Render_textured_meshes.ipynb on Google Colab, loading in exactly the same pytorch3d version I have installed on my Google Drive, I don't get this error and I can use CUDA.

I'm aware that I may need to provide further information in this question, but I am not sure what to provide at the moment. Please could you let me know in the responses?

Thanks a lot!

**Comment by bottler** [comment]
When PyTorch3D is built, it is compiled for a particular set of CUDA capabilities. This error probably means the GPU you are using has a compute capability different from the ones PyTorch3D was built for.

I think you are using google colab exclusively, and if you are using our tutorials you will be installing with `!pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'` which builds from source without setting CUDA capabilities. (This takes about 10 minutes I think. Is that about right ?) When this is run, the build will only be for the specific GPU present on the machine (executor). It should work.

When you use a GPU in colab, there is no guarantee of what GPU type you will get. I wonder if you are somehow building with one type of GPU in one session and then using it with a different type in another session. For example, does colab timeout when you stop using it (or archive your session), after which you continue your session, but this might end up with a different GPU? If that's the case, we can set some environment variables to force the build to include all the possible architectures.

**Comment by hamid162** [comment]
Thanks for your response. Yes that's right, I installed using !pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable', but set the install target to be on my personal Google Drive. That way whenever I had to use PyTorch3D, I could just load in the installed module.

When I run the tutorials again, I don't run !pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable' each time. I load in the installed module, and it works just fine for the tutorials. It's only when I apply it to my own code, I experience the CUDA error.

I think I am getting different GPUs each time I use Colab, but it doesn't seem to affect the tutorial scripts since I don't get the CUDA error with those.

**Comment by bottler** [comment]
I think the easiest explanations are (a) some of the tutorials might not be using the compiled parts of PyTorch3D. There are lots of functions in PyTorch3D which are written in Python and so will work anyway if the device does not match. (b) Just luck.

I think Colab is currently using CUDA 10.1. If you want to force a PyTorch3D build to include all the GPUs supported by CUDA 10.1 builds of PyTorch, which is what I think you want, you can set
```
os.environ["NVCC_FLAGS"]="-gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_50,code=compute_50"
```
just before the `pip install`.

For later versions of CUDA, there are more supported devices, you can copy the string from [here](https://github.com/facebookresearch/pytorch3d/blob/master/packaging/linux_wheels/inside.sh#L64).

**Comment by hamid162** [comment]
Thanks, I'll give that a go. Just do clarify, do you mean set: 

`os.environ["NVCC_FLAGS"]="-gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_50,code=compute_50"`

before running:

`'git+https://github.com/facebookresearch/pytorch3d.git@stable'`

to install PyTorch3D again?

If so, won't the `os.environ["NVCC_FLAGS"]=` command just be valid for that particular Colab session only? Meaning if I connect to another Colab session, i'd have to do this again each time?

**Comment by bottler** [comment]
Yes, setting the variable before the install is what I mean. Yes, it is only valid for one session, affecting the build done in that session.

But I don't know what you mean by "each time". I thought in most sessions you were not installing PyTorch3D from source, but rather loading the build from your google drive. What I am suggesting is that you do this once and save that **new** build of PyTorch3D to your google drive (which will be a larger file, containing support for many GPUs). Then you can load it using your existing code and all will be fine.

**Comment by hamid162** [comment]
Amazing! It worked very well. Thanks so much!
