### ISSUE TITLE
About "projects/nerf":  Failed to build the environment.

### ISSUE THREAD

**Issue by XiaoqiangZhou** [facebookresearch/pytorch3d#827]
Thanks for developing NeRF with the Pytorch3d framework.

However, My program failed with a error message after I run the nerf training script provided in the README. Could you please help me with it?

My script are `CUDA_VISIBLE_DEVICES=0 python train_nerf.py --config-name lego`.  And the error messages are:

> Loading dataset lego, image size=[800, 800] ...
> Precaching 100 ray bundles ...
> Error executing job with overrides: []
> Traceback (most recent call last):
>   File "train_nerf.py", line 144, in main
>     model.precache_rays(cache_cameras, cache_camera_hashes)
>   File "/data/name/pytorch3d/projects/nerf/nerf/nerf_renderer.py", line 193, in precache_rays
>     cache_camera_hashes,
>   File "/data/name/pytorch3d/projects/nerf/nerf/raysampler.py", line 228, in precache_rays
>     chunksize=full_chunksize,
>   File "/data/name/pytorch3d/projects/nerf/nerf/raysampler.py", line 326, in forward
>     full_ray_bundle = self._grid_raysampler(cameras)
>   File "/data1/path_to_conda/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/data1/path_to_conda/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/pytorch3d/renderer/implicit/raysampling.py", line 131, in forward
>     cameras, xy_grid, self._min_depth, self._max_depth, self._n_pts_per_ray
>   File "/data1/path_to_conda/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/pytorch3d/renderer/implicit/raysampling.py", line 286, in _xy_to_ray_bundle
>     min_depth, max_depth, n_pts_per_ray, dtype=xy_grid.dtype, device=xy_grid.device
> RuntimeError: CUDA error: no kernel image is available for execution on the device
> CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Environment info:
GPU: RTX 3090
torch: 1.9.0
cuda: 11.0
I have installed the pytorch3d from source code in Github, since some functions are not updated in prebuilt packages.

Thanks!

**Comment by bottler** [comment]
Your GPU has compute capability 8.6, which is not supported by CUDA 11.0. I think you need to start a new environment and use CUDA 11.1, then reinstall PyTorch. Check that some PyTorch commands work on the gpu. Then you can install PyTorch3D from source or from binaries.

**Comment by bottler** [comment]
By the way, if you want binaries with new features (since v0.5.0) you can use the nightly builds.

**Comment by XiaoqiangZhou** [comment]
Thanks for your help! As you suggested, I re-installed the PyTorch to make sure it works.  However, there is still a small problem with the pytorch3d. 

I installed the pytorch3d with command `conda install pytorch3d -c pytorch3d-nightly`, After that, I tried to run the nerf code and got the error message:

`ModuleNotFoundError: No module named 'pytorch3d.renderer.implicit.sample_pdf'`

In my local machine, I do not find the `sample_pdf.py` file in `/data1/path_to_conda/anaconda3/envs/pytorch3d/lib/python3.7/site-packages/pytorch3d/renderer/implicit/` folder. However, I find the `sample_pdf.py` file does exist in your github repo. 

Could you please tell me why command `conda install pytorch3d -c pytorch3d-nightly` doesn't install the `sample_pdf` file? Do I need to download this file and put it in my local machine manually? 

Thanks!

**Comment by XiaoqiangZhou** [comment]
Well... I tried to copy the `sample_pdf.py` from the GitHub repo to my local machine directly, but got the error when I run the nerf code:
 File "/data1/path_to_conda/envs/pytorch3d/lib/python3.7/site-packages/pytorch3d/renderer/implicit/sample_pdf.py", line 57, in sample_pdf
    _C.sample_pdf(
AttributeError: module 'pytorch3d._C' has no attribute 'sample_pdf'
`

**Comment by bottler** [comment]
It seems like you have an old nightly build, older than a few nights. What is the creation date of `/data1/path_to_conda/envs/pytorch3d/lib/python3.7/site-packages/pytorch3d/_C<something>.so` ?

I think the cause could be conda package caching. You could try a new environment and make the pytorch3d install be
```
CONDA_PKGS_DIRS=$(mktemp -d) conda install -c pytorch3d-nightly pytorch3d
```

**Comment by XiaoqiangZhou** [comment]
@bottler Thanks for your suggestion. The creation data of `path/site-packages/pytorch3d/_C<something>.so` is **Sep. 7th**. However, all of the creation data of python source files in folder `path/site-packages/pytorch3d/` are **Aug. 13th** (except the folder `__pycache__`). Therefore, I suspect that the `_C<something>.so` cannot include the recently updated changes in the github. 

Also, I tried to uninstall the pytorch3d from both pip list and conda list, and install the pytorch3d again with `CONDA_PKGS_DIRS=$(mktemp -d) conda install -c pytorch3d-nightly pytorch3d`, but it still not works. The creation date of files in folder `path/site-packages/pytorch3d/` are still Aug. 13th.

It's worth mentioning that the first time I tried to install pytorch3d is on **Sep. 2nd**, and I have never tried to install this package in August. 

Do you have any other suggestions for this issue? Thanks!

**Comment by bottler** [comment]
I think I now understand the issue. The nightly build did not follow the recent renaming of the "main" branch from "master", so had new packages without the latest changes. It should now have been fixed.

**Comment by XiaoqiangZhou** [comment]
@bottler  Thanks for your help! As you suggested, I retry to install the pytorch3d with `conda install pytorch3d -c pytorch3d-nightly` and the problem has been solved. Thanks!
