### ISSUE TITLE
"from pytorch3d import _C" is expecting libcudart.so.10.1 instead of libcudart.so.10.2

### ISSUE THREAD

**Issue by Tariq-Abuhashim** [facebookresearch/pytorch3d#833]
## 🐛 Bugs / Unexpected behaviors
I have followed pytorch3d installation instructions. First as in README.md, but generated the same error, and then by making minor changes:
```
conda create -n pytorch3d python=3.6
conda activate pytorch3d
conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=10.2 -c pytorch
conda install -c fvcore -c iopath -c conda-forge fvcore iopath

conda install -c bottler nvidiacub

# Demos and examples
conda install jupyter
pip install scikit-image matplotlib imageio plotly opencv-python

# Tests/Linking
pip install chardet
pip install idna
pip install black 'isort<5' flake8 flake8-bugbear flake8-comprehensions

# Anaconda Cloud
conda install pytorch3d -c pytorch3d
```

However, my code returns a libcudart linking error when trying to import pytorch3d.renderer.

## Instructions To Reproduce the Issue:

I am trying to run the following code (from my_code.py) :
```
# imports
import torch
from pytorch3d.transforms.so3 import (
    so3_relative_angle,
)
from pytorch3d.renderer.cameras import (
    SfMPerspectiveCameras,
)
```
The commands I ran were:
```
conda activate pytorch3d
python3 my_code.py
```

The error:
```
Traceback (most recent call last):
  File "my_code.py", line 7, in <module>
    from pytorch3d.renderer.cameras import (
  File "/home/mrt/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/pytorch3d/renderer/__init__.py", line 3, in <module>
    from .blending import (
  File "/home/mrt/anaconda3/envs/pytorch3d/lib/python3.6/site-packages/pytorch3d/renderer/blending.py", line 9, in <module>
    from pytorch3d import _C
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory
```

## Troubleshooting:

Locating libcudart.so:
```
$ locate libcudart
/home/mrt/anaconda3/envs/pytorch3d/lib/libcudart.so
/home/mrt/anaconda3/envs/pytorch3d/lib/libcudart.so.10.2
/home/mrt/anaconda3/envs/pytorch3d/lib/libcudart.so.10.2.89
```

System information:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89
```

**Comment by hailsong** [comment]
I have the same issue 😥

**Comment by Tariq-Abuhashim** [comment]
I executed the following lines after activating the previously created environment:
```
conda activate pytorch3d
curl -LO https://github.com/NVIDIA/cub/archive/1.10.0.tar.gz
tar xzf 1.10.0.tar.gz
pip install 'git+https://github.com/facebookresearch/pytorch3d.git@stable'
```

Then added the following line on top of my file after importing os:
```
os.environ["CUB_HOME"] = os.getcwd() + "/cub-1.10.0"
```

I can not regenerate that error anymore.

**Comment by bottler** [comment]
@Tariq-Abuhashim It sounds like this was sorted by building PyTorch3D from source, so I will close this issue.

@hailsong If you need help, please open a new issue explaining what you did, what is wrong, and the output of `conda info` and `conda list`.

**Comment by kajal-puri** [comment]
Hi,

I happen to face the same issue while installing PyTorch3d with conda and pip.
But when I tried installing it with the Python/Jupyter notebook code snippet, that worked for me perfectly. 
Here is what I've used, which is mentioned on their [Installation page](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md) as well.

```
import sys
import torch
version_str="".join([
    f"py3{sys.version_info.minor}_cu",
    torch.version.cuda.replace(".",""),
    f"_pyt{torch.__version__[0:5:2]}"
])
!pip install pytorch3d -f https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/{version_str}/download.html
```
